# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'LancheTop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LancheTop
	pod 'Alamofire'
	pod 'Moya'
	pod 'ObjectMapper'
    pod 'Moya-ObjectMapper'
    
  # Cache Image	
	pod 'Kingfisher', '~> 3.0'
    

  target 'LancheTopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LancheTopUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
